status:
    path:               /status
    defaults:           { _controller: TravelDiaryApiBundle:Status:status }
    methods:            [GET]

createTrip:
    path:               /trips
    defaults:           { _controller: TravelDiaryApiBundle:Trip:process, tripUUID: '' }
    methods:            [POST]

updateTrip:
    path:               /trip/{tripUUID}
    defaults:           { _controller: TravelDiaryApiBundle:Trip:process }
    methods:            [PUT]
    requirements:
        tripUUID:        "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"

listTrips:
    path:               /trips
    defaults:           { _controller: TravelDiaryApiBundle:Trip:list }
    methods:            [GET]

getTrip:
    path:               /trip/{trip_id}
    defaults:           { _controller: TravelDiaryApiBundle:Trip:get }
    methods:            [GET]
    requirements:
        trip_id:        "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"

removeTrip:
    path:               /trip/{trip_id}
    defaults:           { _controller: TravelDiaryApiBundle:Trip:remove }
    methods:            [DELETE]
    requirements:
        trip_id:        "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"

createToken:
    path:               /token
    defaults:           { _controller: TravelDiaryApiBundle:Token:create }
    methods:            [POST]

deleteToken:
    path:               /token
    defaults:           { _controller: TravelDiaryApiBundle:Token:delete }
    methods:            [DELETE]

listEnums:
    path:               /enums
    defaults:           { _controller: TravelDiaryApiBundle:Enum:list }
    methods:            [GET]

createTripRecord:
    path:               /trip/{idTrip}/records
    defaults:           { _controller: TravelDiaryApiBundle:TripRecord:process, idTripRecord: '' }
    methods:            [POST]
    requirements:
        idTrip:         "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"

updateTripRecord:
    path:               /trip/{idTrip}/record/{idTripRecord}
    defaults:           { _controller: TravelDiaryApiBundle:TripRecord:process, idTripRecord: '' }
    methods:            [PUT]
    requirements:
        idTrip:         "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
        idTripRecord:   "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"

removeTripRecord:
    path:               /trip/{idTrip}/record/{idTripRecord}
    defaults:           { _controller: TravelDiaryApiBundle:TripRecord:remove }
    methods:            [DELETE]
    requirements:
        idTrip:         "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
        idTripRecord:   "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"

getTripRecord:
    path:               /trip/{idTrip}/record/{idTripRecord}
    defaults:           { _controller: TravelDiaryApiBundle:TripRecord:detail }
    methods:            [GET]
    requirements:
        idTrip:         "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
        idTripRecord:   "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"