status:
    path:               /status
    defaults:           { _controller: TravelDiaryApiBundle:Status:status }
    methods:            [GET]

createTrip:
    path:               /trip
    defaults:           { _controller: TravelDiaryApiBundle:Trip:create }
    methods:            [POST]

updateTrip:
    path:               /trip/{trip_id}
    defaults:           { _controller: TravelDiaryApiBundle:Trip:update }
    methods:            [PUT]
    requirements:
        trip_id:        \d+

listTrips:
    path:               /trips
    defaults:           { _controller: TravelDiaryApiBundle:Trip:list }
    methods:            [GET]

getTrip:
    path:               /trip/{trip_id}
    defaults:           { _controller: TravelDiaryApiBundle:Trip:get }
    methods:            [GET]
    requirements:
        trip_id:        \d+

removeTrip:
    path:               /trip/{trip_id}
    defaults:           { _controller: TravelDiaryApiBundle:Trip:remove }
    methods:            [DELETE]
    requirements:
        trip_id:        \d+

createToken:
    path:               /token
    defaults:           { _controller: TravelDiaryApiBundle:Token:create }
    methods:            [POST]

deleteToken:
    path:               /token
    defaults:           { _controller: TravelDiaryApiBundle:Token:delete }
    methods:            [DELETE]
