services:

    travel_diary_api.security.api_user_provider:
        class: TravelDiary\ApiBundle\Security\ApiUserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]

    travel_diary_api.security.api_authenticator:
        class: TravelDiary\ApiBundle\Security\ApiAuthenticator
        public: false
        arguments: ["@security.http_utils"]
        tags:
            - { name: monolog.logger }