services:

    travel_diary_api.security.api_user_provider:
        class: TravelDiary\ApiBundle\Security\ApiUserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]

    travel_diary_api.security.api_authenticator:
        class: TravelDiary\ApiBundle\Security\ApiAuthenticator
        public: false
        arguments: ["@security.http_utils"]
        tags:
            - { name: monolog.logger }

    app.request_listener:
        class: TravelDiary\ApiBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: ['@snc_redis.cache']