FORMAT: 1A
HOST: http://api-traveldiary.jakubdubec.me/v1

# Travel Diary API

Simple RESTful API service for synchronization of traveling diaries between mobile application and database server.

## Database diagram

![Entity relation diagram](https://github.com/MTAA-FIIT/TravelDiary-Api/raw/master/_docs/EER_v4.png)

## Mockups

![Mockups](https://github.com/MTAA-FIIT/TravelDiary-Api/raw/master/_docs/Mockups_v1.jpg)

## Credentials

 - [Jakub Dubec](mailto:xdubec@stuba.sk)

## Token [/token]

### Create token [POST]

+ Request (application/json)

    + Headers

        X-TravelDiary-Device: UUID4-OF-DEVICE

    + Attributes

        + email: `jakub.dubec@gmail.com` (required, string) - Email of user
        + password: `$2y$13$jugbchb1Jxk3/tk92ui.2OioNoicE4XxH4KO.LxcVDXl3kJ55DUUC` (required, string) - mbcrypt (13 iterations) hash of user password

+ Response 201 (application/json)

        {
            "token":"0ddd79db-6ad2-4bf3-b0b9-a3ebb45f5dad"
        }

+ Response 400 (application/json)

        {
            "message": "Empty body request!"
        }

+ Response 401 (application/json)

        {
            "message":"Invalid credentials!"
        }

+ Response 500 (application/json)

        {
            "message": "Error description"
        }

### Remove token [DELETE]

+ Request

    + Headers

        X-TravelDiary-Device: UUID4-OF-DEVICE

+ Response 204 (application/json)

+ Response 403 (application/json)

        {
            "message":"Forbidden!"
        }

+ Response 500 (application/json)

        {
            "message": "Error description"
        }

## Enums [/enums]

### List all enums [GET]

+ Request

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

+ Response 200 (application/json)


        {
            "statuses":
            [
                {
                    "code": "IN_PROGRESS",
                    "description": "Trip is in progress"
                }
            ],
            "trip_types":
            [
                {
                    "code": "CAMPING",
                    "description": "A new camping record"
                }
            ]
        }


+ Response 403 (application/json)

        {
            "message":"Forbidden!"
        }

## Trips Collection [/trips]

### List all trips [GET]

+ Request

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

+ Response 200 (application/json)

        [
            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "status": "PLANNED",
                "privacy": "PUBLIC"
            }
        ]

+ Response 403 (application/json)

        {
            "message":"Forbidden!"
        }

### Create a New Trip [POST]

+ Request (application/json)

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

    + Attributes

        + id: `b429b294-ac24-423f-bb5a-a90998dd7612` (required, string) - Generated identificator for trip UUID4
        + name: `Norway 2015` (required, string) - Name of the trip
        + destination: `Trolltunga, Odda, Norway` (required, string) - Destination of trip
        + description: `A low-cost hitchhiking trip through the Scandinavia and the Baltic states.` (required, string) - Description of trip
        + start_date: `2015-07-12` (required, string) - Start date of trip in format Y-m-d
        + estimated_arrival_date: `2015-08-04` (required, string) - Estimated arrival date in format Y-m-d
        + status: `PLANNED` (required, enum) - Status of trip
            - `PLANNED` (string)
            - `IN_PROGRESS` (string)
            - `CANCELED` (string)
            - `FINISHED` (string)
        + privacy: `PUBLIC` (required, enum) - Privacy setting for trip
            - `PUBLIC` (string)
            - `MEMBER` (string)
            - `PRIVATE` (string)
        + users: (required, array) - List of trip owners

+ Response 201 (application/json)

    + Body

            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "status": "PLANNED",
                "privacy": "PUBLIC",
                "description": "A low-cost hitchhiking trip through the Scandinavia and the Baltic states.",
                "start_date": "2015-07-12",
                "estimated_arrival_date": "2015-08-04",
                "records":
                [
                    {
                        "id": "5b973fb3-5267-4e30-9d01-f96e3fde439a",
                        "type": "CAMPING",
                        "day": "2015-07-11T00:00:00+0200"
                    }
                ],
                "users":
                [
                    {
                        "id": 1,
                        "name": "Jakub Dubec",
                        "email": "jakub.dubec@gmail.com"
                    }
                ],
                "created_at": "2016-03-29T21:54:03+0200",
                "updated_at": "2016-03-29T22:06:40+0200"
            }

+ Response 400 (application/json)

            {
                "message": "Empty body request!"
            }

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "Invalid input!",
                "invalid_fields": [ 'updaated_at' ]
            }

+ Response 500 (application/json)

    + Body

            {
                "message": "User friendly message describing error",
            }

## Trip [/trips/{trip_id}]

+ Parameters
    + trip_id: `b429b294-ac24-423f-bb5a-a90998dd7612` (string) - ID of the trip UUID4

### View a Trip detail [GET]

+ Request

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4


+ Response 200 (application/json)

    + Body

            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "status": "PLANNED",
                "privacy": "PUBLIC",
                "description": "A low-cost hitchhiking trip through the Scandinavia and the Baltic states.",
                "start_date": "2015-07-12",
                "estimated_arrival_date": "2015-08-04",
                "records":
                [
                    {
                        "id": "5b973fb3-5267-4e30-9d01-f96e3fde439a",
                        "type": "CAMPING",
                        "day": "2015-07-11T00:00:00+0200"
                    }
                ],
                "users":
                [
                    {
                        "id": 1,
                        "name": "Jakub Dubec",
                        "email": "jakub.dubec@gmail.com"
                    }
                ],
                "created_at": "2016-03-29T21:54:03+0200",
                "updated_at": "2016-03-29T22:06:40+0200"
            }

### Update a Trip detail [PUT]

+ Request (application/json)

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

    + Attributes

        + id: `b429b294-ac24-423f-bb5a-a90998dd7612` (required, string) - Generated identificator for trip UUID4
        + name: `Norway 2015` (required, string) - Name of the trip
        + destination: `Trolltunga, Odda, Norway` (required, string) - Destination of trip
        + description: `A low-cost hitchhiking trip through the Scandinavia and the Baltic states.` (required, string) - Description of trip
        + start_date: `2015-07-12` (required, string) - Start date of trip in format Y-m-d
        + estimated_arrival_date: `2015-08-04` (required, string) - Estimated arrival date in format Y-m-d
        + status: `PLANNED` (required, enum) - Status of trip
            - `PLANNED` (string)
            - `IN_PROGRESS` (string)
            - `CANCELED` (string)
            - `FINISHED` (string)
        + privacy: `PUBLIC` (required, enum) - Privacy setting for trip
            - `PUBLIC` (string)
            - `MEMBER` (string)
            - `PRIVATE` (string)
        + users: (required, array) - List of trip owners

+ Response 200 (application/json)

    + Body

            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "status": "PLANNED",
                "privacy": "PUBLIC",
                "description": "A low-cost hitchhiking trip through the Scandinavia and the Baltic states.",
                "start_date": "2015-07-12",
                "estimated_arrival_date": "2015-08-04",
                "records":
                [
                    {
                        "id": "5b973fb3-5267-4e30-9d01-f96e3fde439a",
                        "type": "CAMPING",
                        "day": "2015-07-11T00:00:00+0200"
                    }
                ],
                "users":
                [
                    {
                        "id": 1,
                        "name": "Jakub Dubec",
                        "email": "jakub.dubec@gmail.com"
                    }
                ],
                "created_at": "2016-03-29T21:54:03+0200",
                "updated_at": "2016-03-29T22:06:40+0200"
            }

+ Response 400 (application/json)

            {
                "message": "Empty body request!"
            }

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 404 (application/json)

            {
                "message": "Not found!",
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "Invalid input!",
                "invalid_fields": [ 'updaated_at' ]
            }

+ Response 500 (application/json)

    + Body

            {
                    "message": "User friendly message describing error",
            }

### Delete trip [DELETE]

+ Request

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

+ Response 204

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Not found!",
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612"
            }

+ Response 500 (application/json)

    + Body

            {
                "message": "User friendly message describing error",
            }

## Trip Records Collection [/trips/{trip_id}/records]

+ Parameters
    + trip_id: `bf00ffa4-651b-4bb4-8090-76cac7088c95` (string) - ID of the trip in form of SHA256 hash

### Create trip record [POST]
+ Request (application/json)

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

    + Attributes

        + id: `b429b294-ac24-423f-bb5a-a90998dd7612` (required, string) - Generated identificator for trip record UUID4
        + type: `CAMPING` (required, RecordTypeEnum) - Type of record
        + day: `2016-03-02` (required, string) - Day of the trip
        + description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis arcu egestas neque porttitor fringilla. ` (required, string) - Message
        + coordinates: (optional, Coordinates) - Current location
        + photos: (optional, array[Photo]) - Array of photos

+ Response 201 (application/json)

    + Headers

            Location: /trips/bf00ffa4-651b-4bb4-8090-76cac7088c95/records/b429b294-ac24-423f-bb5a-a90998dd7612

    + Body

            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "type": "CAMPING",
                "day": "2016-03-02",
                "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis arcu egestas neque porttitor fringilla.",
                "coordinates":
                {
                    "latitude": 48.158564899999995,
                    "longitude": 17.064523299999998,
                    "altitude": 320
                },
                "photos":
                [
                    {
                        "data": "..."
                    },
                ],
                "author": {
                	"id": 1,
                	"name": "Jakub Dubec",
                	"email": "jakub.dubec@gmail.com"
                }
            }

+ Response 400 (application/json)

            {
                "message": "Empty body request!"
            }

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "Invalid input!",
                "invalid_fields": [ 'cordinates', 'status' ]
            }

+ Response 500 (application/json)

    + Body

            {
                "message": "Unable to save record. Please try it later."
            }

## Trip record detail [/trips/{trip_id}/records/{record_id}]

+ Parameters
    + trip_id: `bf00ffa4-651b-4bb4-8090-76cac7088c95` (string) - ID of the trip UUID4
    + record_id: `b429b294-ac24-423f-bb5a-a90998dd7612` (string) - ID of the trip record UUID4

### Get trip record details [GET]

+ Request

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

+ Response 200 (application/json)

    + Body

            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "type": "CAMPING",
                "day": "2016-03-02",
                "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis arcu egestas neque porttitor fringilla.",
                "coordinates":
                {
                    "latitude": 48.158564899999995,
                    "longitude": 17.064523299999998,
                    "altitude": 320
                },
                "photos":
                [
                    {
                        "data": "..."
                    },
                ],
                "author": {
                	"id": 1,
                	"name": "Jakub Dubec",
                	"email": "jakub.dubec@gmail.com"
                }
            }

+ Response 400 (application/json)

            {
                "message": "Empty body request!"
            }

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Trip record not found!",
            }


### Update trip record [PUT]

+ Request (application/json)

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4


    + Attributes

        + type: `CAMPING` (optional, RecordTypeEnum) - Type of record
        + day: `2016-03-02` (optional, string) - Day of the trip
        + description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis arcu egestas neque porttitor fringilla. ` (optional, string) - Message
        + coordinates: (optional, Coo§rdinates) - Current location
        + photos: (optional, array[Photo]) - Array of photos

+ Response 201 (application/json)

    + Body

            {
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612",
                "type": "CAMPING",
                "day": "2016-03-02",
                "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec facilisis arcu egestas neque porttitor fringilla.",
                "coordinates":
                {
                    "latitude": 48.158564899999995,
                    "longitude": 17.064523299999998,
                    "altitude": 320
                },
                "photos":
                [
                    {
                        "data": "..."
                    },
                ],
                "author": {
                	"id": 1,
                	"name": "Jakub Dubec",
                	"email": "jakub.dubec@gmail.com"
                }
            }

+ Response 400 (application/json)

            {
                "message": "Empty body request!"
            }

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 404 (application/json)

    + Body

            {
                "message": "Trip record not found!"
            }

+ Response 422 (application/json)

    + Body

            {
                "message": "Invalid input!",
                "invalid_fields": [ 'cordinates', 'status' ]
            }


+ Response 500 (application/json)

    + Body

            {
                "message": "Unable to update trip record. Please try it later."
            }

### Delete trip [DELETE]

+ Request

    + Headers

        X-TravelDiary-Device: 6c4af814-04e2-4ddb-b625-b64b77dcd228
        X-TravelDiary-Token: 42653452-447b-4292-b5e6-acd127746bb4

+ Response 204

+ Response 403 (application/json)

            {
                "message": "Forbidden!"
            }

+ Response 404 (application/json)

        + Body

            {
                "message": "Not found!",
                "id": "b429b294-ac24-423f-bb5a-a90998dd7612"
            }

+ Response 500 (application/json)

        + Body

            {
                "message": "User friendly message describing error",
            }

## Status [/status]

Application is testing server by calling this endpoint.

### Get stats [GET]

+ Response 200 (application/json)

            {
                "stats": {
                    "trips": 10,
                    "records": 145,
                    "users": 2
                },
                "timestamp": 1456960832
            }

# Data Structures

## TripStatusEnum (enum[string])
    - `PLANNED`
    - `IN_PROGRESS`
    - `CANCELED`
    - `FINISHED`

## RecordTypeEnum (enum[string])
    - `CAMPING`
    - `BIVOUAC`
    - `HOTEL`
    - `ACTIVITY`
    - `UPDATE`
    - `CHECK_IN`
    - `NOTE`

## Coordinates (object)
    - latitute (required, number)
    - longitude (required, number)
    - altitude (optional, number)

## Photo (object)
    - data (required, string) - BASE64 of image
