FORMAT: 1A
HOST: http://api-traveldiary.jakubdubec.me

# Travel Diary API

Simple RESTful API service for synchronization of traveling diaries between mobile application and database server.

## Enums [/enums]

### List all enums [GET]

+ Response 200 (application/json)

        {
            "statuses":
            [
                {
                    "code": "IN_PROGRESS",
                    "description": "Trip is in progress"
                }
            ],
            "trip_types":
            [
                {
                    "code": "CAMPING",
                    "description": "A new camping record"
                }
            ]
        }

## Trips Collection [/trips]

### List all trips [GET]

+ Response 200 (application/json)

        [
            {
                "id": "565d93b922bfeb48dde3252605548e5e91a6ad0c1ee479e178a465425e673644",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "description": "An low-cost hitchhiking trip through the Scandinavia and the Baltic states.",
                "start_date": "2015-07-7",
                "estimated_arrival": "2015-08-01",
                "created_at": "2016-02-28T12:48:15+00:00",
                "updated_at": null
            }
        ]

### Create a New Trip [POST]

+ Request (application/json)

    + Attributes

        + id: 565d93b922bfeb48dde3252605548e5e91a6ad0c1ee479e178a465425e673644 (required, string) - Generated identificator for trip (SHA256)
        + name: Norway 2015 (required, string) - Name of the trip
        + destination: Trolltunga, Odda, Norway (required, string) - Destination of trip
        + description: `A low-cost hitchhiking trip through the Scandinavia and the Baltic states.` (required, string) - Description of trip
        + start_date: `2015-07-12` (required, string) - Start date of trip in format Y-m-d
        + estimated_arrival: `2015-08-04` (required, string) - Estimated arrival date in format Y-m-d
        + statuts: (enum[string])

            + Members
                + `PLANNED`
                + `IN_PROGRESS`
                + `CANCELED`
                + `FINISHED`

+ Response 201 (application/json)

    + Headers

            Location: /trips/565d93b922bfeb48dde3252605548e5e91a6ad0c1ee479e178a465425e673644

    + Body

            {
                "id": "565d93b922bfeb48dde3252605548e5e91a6ad0c1ee479e178a465425e673644",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "description": "An low-cost hitchhiking trip through the Scandinavia and the Baltic states.",
                "start_date": "2015-07-7"
            }

+ Response 500 (application/json)

    + Body

            {
                "message": "User friendly message describing error",
            }

+ Response 400 (application/json)

    + Body

            {
                "message": "Invalid input!",
                "invalid_fields": [ 'updaated_at' ]
            }

## Trip [/trips/{trip_id}]

+ Parameters
    + trip_id (string) - ID of the trip in form of SHA256 hash

### View a Trip detail [GET]

+ Response 200 (application/json)

    + Body

            {
                "id": "565d93b922bfeb48dde3252605548e5e91a6ad0c1ee479e178a465425e673644",
                "name": "Norway 2015",
                "destination": "Trolltunga, Odda, Norway",
                "description": "An low-cost hitchhiking trip through the Scandinavia and the Baltic states.",
                "start_date": "2015-07-7",
                "estimated_arrival": "2015-08-01",
                "created_at": "2016-02-28T12:48:15+00:00",
                "updated_at": null
            }
