landing_page:
    path:               /
    defaults:           { _controller: TravelDiaryInterfaceBundle:Default:index }

subcategoryRouting:
    resource:           "@TravelDiaryInterfaceBundle/Resources/config/routing/trip.yml"

authRouting:
    resource:           "@TravelDiaryInterfaceBundle/Resources/config/routing/auth.yml"

deviceRouting:
    resource:           "@TravelDiaryInterfaceBundle/Resources/config/routing/device.yml"

dashboard:
    path:               /dashboard
    defaults:           { _controller: TravelDiaryInterfaceBundle:Dashboard:dashboard }

monitor:
    path:               /monitor
    defaults:           { _controller: TravelDiaryInterfaceBundle:Monitor:overview }
    methods:            [ GET ]
