landing_page:
    path:               /
    defaults:           { _controller: TravelDiaryInterfaceBundle:Default:index }

subcategoryRouting:
    resource:           "@TravelDiaryInterfaceBundle/Resources/config/routing/trip.yml"

authRouting:
    resource:           "@TravelDiaryInterfaceBundle/Resources/config/routing/auth.yml"

dashboard:
    path:               /dashboard
    defaults:           { _controller: TravelDiaryInterfaceBundle:Dashboard:dashboard }
