services:

    travel_diary_interface.twig.gravatar_extension:
        class: TravelDiary\InterfaceBundle\Twig\GravatarExtension
        tags:
            - { name: twig.extension }

    travel_diary_interface.twig.google_maps_extension:
        class: TravelDiary\InterfaceBundle\Twig\GoogleMapsExtension
        tags:
            - { name: twig.extension }
        arguments: [ "%google_browser_api_key%" ]