services:

    # Twig services

    travel_diary_interface.twig.gravatar_extension:
        class: TravelDiary\InterfaceBundle\Twig\GravatarExtension
        tags:
            - { name: twig.extension }

    travel_diary_interface.twig.google_maps_extension:
        class: TravelDiary\InterfaceBundle\Twig\GoogleMapsExtension
        tags:
            - { name: twig.extension }
        arguments: [ "%google_browser_api_key%" ]

    # Form serializer (I have no fucking idea what have I done)

    travel_diary_interface.dependency_injection.form_errors_serializer:
        class: TravelDiary\InterfaceBundle\DependencyInjection\FormErrorsSerializer

    # My own client API factory! Sweet baby!

    travel_diary_client.api_client_factory:
        class: TravelDiary\ApiClient\ApiClientFactory
        arguments: [ "%api_url%" ]
