services:
#    travel_diary_interface.example:
#        class: TravelDiary\InterfaceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  travel_diary_interface.twig.gravatar_extension:
    class: TravelDiary\InterfaceBundle\Twig\GravatarExtension
    tags:
      - { name: twig.extension }