travel_diary_interface:
    resource:     "@TravelDiaryInterfaceBundle/Resources/config/routing.yml"
    prefix:       /frontend

travel_diary_api:
    resource:     "@TravelDiaryApiBundle/Resources/config/routing.yml"
    prefix:       /api/v1