travel_diary_interface:
    resource:       "@TravelDiaryInterfaceBundle/Resources/config/routing.yml"
    prefix:         /frontend
#    host:           "www.{domain}"
#    requirements:   "%domain%"

travel_diary_api:
    resource:       "@TravelDiaryApiBundle/Resources/config/routing.yml"
    prefix:         /api/v1
#    host:           "api.{domain}"
#    requirements:   "%domain%"