travel_diary_interface:
    resource:       "@TravelDiaryInterfaceBundle/Resources/config/routing.yml"
    host:           www.%domain%

travel_diary_api:
    resource:       "@TravelDiaryApiBundle/Resources/config/routing.yml"
    prefix:         /v1
    host:           api.%domain%