# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        TravelDiary\CoreBundle\Entity\User:
            algorithm: bcrypt
            iterations: 13

    role_hierarchy:
        USER_ROLE:
        ADMINISTRATOR_ROLE: USER_ROLE

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_provider:
            entity:
                class: TravelDiaryCoreBundle:User
                property: usrEmail
        api_user_provider:
            id: travel_diary_api.security.api_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_firewall:
            host: ^api\.
            anonymous: ~
            stateless: true
            simple_preauth:
                authenticator: travel_diary_api.security.api_authenticator
            provider: api_user_provider

        frontend_firewall:
            host: ^www\.
            anonymous: ~
            provider: database_provider
            form_login:
                login_path: login
                check_path: check
                default_target_path: dashboard
            logout:
                path:   logout
                target: landing_page

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/v1/status$, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: ^api\. }
        - { path: ^/v1/token$, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: ^api\. }
        - { path: ^/auth/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: ^www\. }
        - { path: ^/auth/logout$, roles: USER_ROLE, requires_channel: https, host: ^www\. }