# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        TravelDiary\CoreBundle\Entity\User:
            algorithm: bcrypt
            iterations: 13

    role_hierarchy:
        USER_ROLE:
        ADMINISTRATOR_ROLE: USER_ROLE

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_provider:
            entity:
                class: TravelDiaryCoreBundle:User
                property: usrEmail

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        frontend_firewall:
            pattern: ^/
            anonymous: ~
            provider: database_provider
            form_login:
                login_path: login
                check_path: check
                default_target_path: dashboard
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/frontend/auth/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/frontend/auth/logout$, roles: USER_ROLE, requires_channel: https }