TravelDiary\CoreBundle\Entity\Device:
    repositoryClass: TravelDiary\CoreBundle\Entity\DeviceRepository
    type: entity
    table: device
    indexes:
        FK__user:
            columns:
                - id_user
    uniqueConstraints:
        UNIQUE_dev_uuid:
            columns:
                - dev_uuid
    id:
        idDevice:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_device
            generator:
                strategy: IDENTITY
    fields:
        devUUID:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: dev_uuid
        devVersion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: dev_version
        devOs:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: dev_os
        devCreatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: dev_createdAt
        devUpdatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: dev_updatedAt
    oneToMany:
        tokens:
            targetEntity: ApiToken
            mappedBy: idDevice
    manyToOne:
        idUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: devices
            joinColumns:
                id_user:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
