TravelDiary\CoreBundle\Entity\Privacy:
    type: entity
    table: privacy
    uniqueConstraints:
        UNIQUE_prv_code:
            columns:
                - prv_code
    id:
        idPrivacy:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_privacy
            generator:
                strategy: IDENTITY
    fields:
        prvCode:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: prv_code
        prvDescription:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: prv_description
    lifecycleCallbacks: {  }
