TravelDiary\CoreBundle\Entity\Record:
    repositoryClass: TravelDiary\CoreBundle\Entity\RecordRepository
    type: entity
    table: record
    indexes:
        FK_record_recordType:
            columns:
                - id_recordType
        FK_record_trip:
            columns:
                - id_trip
        FK_record_user:
            columns:
                - id_user
        INDEX_rec_day:
            columns:
                - rec_day
    uniqueConstraints:
        UNIQUE_rec_uuid:
            columns:
                - rec_uuid
    id:
        idRecord:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_record
            generator:
                strategy: IDENTITY
    fields:
        recUUID:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
            column: rec_uuid
        recDay:
            type: date
            nullable: false
            column: rec_day
        recDescription:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: rec_description
        recLocation:
          type: point
          nullable: true
          column: rec_location
        recAltitude:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: rec_altitude
        recCreatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: rec_createdAt
        recUpdatedAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: rec_updatedAt
    manyToOne:
        idRecordtype:
            targetEntity: Recordtype
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_recordType:
                    referencedColumnName: id_recordType
            orphanRemoval: false
        idTrip:
            targetEntity: Trip
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: tripRecords
            joinColumns:
                id_trip:
                    referencedColumnName: id_trip
            orphanRemoval: false
        idUser:
            targetEntity: TravelDiary\CoreBundle\Entity\User
            cascade: {}
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id_user
            orpganRemoval: false
    oneToMany:
        photos:
            targetEntity: Photo
            mappedBy: idPhoto
    lifecycleCallbacks: {  }
