TravelDiary\CoreBundle\Entity\Role:
    type: entity
    table: role
    uniqueConstraints:
        UNIQUE_rol_name:
            columns:
                - rol_name
    id:
        idRole:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_role
            generator:
                strategy: IDENTITY
    fields:
        rolName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: '0'
            column: rol_name
    lifecycleCallbacks: {  }
