TravelDiary\CoreBundle\Entity\User:
    repositoryClass: TravelDiary\CoreBundle\Entity\UserRepository
    type: entity
    table: user
    indexes:
        FK_user_role:
            columns:
                - id_role
    uniqueConstraints:
        UNIQUE_usr_email:
            columns:
                - usr_email
    id:
        idUser:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        usrUUOD:
            type: string
            nullabe: false
            length: 128
            options:
                fixed: false
            column: usr_uuid
        usrFirstname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: usr_firstName
        usrLastname:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: usr_lastName
        usrEmail:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: usr_email
        usrPassword:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: usr_password
        usrLastseen:
            type: datetime
            nullable: true
            column: usr_lastSeen
        usrCreatedat:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: usr_createdAt
        usrUpdatedat:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: usr_updatedAt
    manyToOne:
        idRole:
            targetEntity: Role
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_role:
                    referencedColumnName: id_role
            orphanRemoval: false
    oneToMany:
        devices:
            targetEntity: Device
            mappedBy: idUser
    manyToMany:
        trips:
            targetEntity: Trip
            inversedBy: users
            joinTable:
                name: user_have_trip
                joinColumns:
                    id_user:
                        referencedColumnName: id_user
                inverseJoinColumns:
                    id_trip:
                        referencedColumnName: id_trip
    lifecycleCallbacks: {  }
