TravelDiary\CoreBundle\Entity\UserHaveTrip:
    type: entity
    table: user_have_trip
    indexes:
        FK_user_have_trip_user:
            columns:
                - id_user
        FK_user_have_trip_trip:
            columns:
                - id_trip
    id:
        idUserHaveTrip:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_user_have_trip
            generator:
                strategy: IDENTITY
    manyToOne:
        idTrip:
            targetEntity: Trip
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_trip:
                    referencedColumnName: id_trip
            orphanRemoval: false
        idUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id_user
            orphanRemoval: false
    lifecycleCallbacks: {  }
