services:

    app.exception_listener:
        class: TravelDiary\CoreBundle\Listener\ErrorListener
        arguments: [ "@logger" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }